google.secret.key.path=classpath:keys/credentials.json
google.oauth.callback.uri=http://localhost:8080/google-drive/oauth

spring.servlet.multipart.max-file-size=10GB
spring.servlet.multipart.max-request-size=10GB