google.secret.key.path=classpath:keys/credentials.json

google.oauth.redirectUri=http://localhost:8080/api/google-drive/oauth/callback
dropbox.oauth.redirectUri=http://localhost:8080/api/dropbox/oauth/callback

spring.servlet.multipart.max-file-size=10GB
spring.servlet.multipart.max-request-size=10GB